### PR TITLE
fix highlight color error

### PR DESCRIPTION
**Pull request by YuriBrunetto**
highlight wasn't working!
### before

error
### after

error fixed

### CODE REVIEW

**Comment by JimmyMultani** [comment]
Hey @YuriBrunetto, highlights seem to be working fine for me.

Can you please provide me with the UI theme you are using, as well as any packages that you may have installed?

Thanks!

**Comment by YuriBrunetto** [comment]
hey @JimmyMultani, sorry for the delay
my currently UI is `One Dark`, one of the default UIs by Atom

don't know why the highlight wasn't working in here, though 😢

**Comment by JimmyMultani** [comment]
@YuriBrunetto, do you have any addons or custom configuration that might hinder the highlight from appearing?

Maybe I can reproduce this on my end.

Thanks!

**Comment by zenorocha** [comment]
This issue looks inactive, @JimmyMultani can you either merge or close it?

**Comment by JimmyMultani** [comment]
I can't reproduce this with a clean install of Atom and Dracula. Closing.

**Pull request closed without merging**
